export const data = [
    {
      name: "Raghu",
      batch: "B42WD2",
      codekata: [
        { day: "Sun", codekata: 13 },
        { day: "Mon", codekata: 10 },
        { day: "Tue", codekata: 17 },
        { day: "Wed", codekata: 5 },
        { day: "Thu", codekata: 25 },
        { day: "Fri", codekata: 10 },
        { day: "Sat", codekata: 2 },
      ],
      webkata: [
        { day: "Sun", webkata: "13" },
        { day: "Mon", webkata: "10" },
        { day: "Tue", webkata: "17" },
        { day: "Wed", webkata: "5" },
        { day: "Thu", webkata: "25" },
        { day: "Fri", webkata: "10" },
        { day: "Sat", webkata: "20" },
      ],
      tasks: [
        { day: "Sun", completed: "1", pending: "28" },
        { day: "Mon", completed: "3", pending: "24" },
        { day: "Tue", completed: "0", pending: "24" },
        { day: "Wed", completed: "2", pending: "22" },
        { day: "Thu", completed: "1", pending: "21" },
        { day: "Fri", completed: "4", pending: "17" },
        { day: "Sat", completed: "2", pending: "15" },
      ],
      webcode1: "8",
      webcode2: "6",
      capstone: "8.5",
      mockInterview1: "3.25",
      mockInterview2: "3.3",
    },
    {
      name: "Anbu",
      batch: "B42WD",
      codekata: [
        { day: "Sun", codekata: "13" },
        { day: "Mon", codekata: "10" },
        { day: "Tue", codekata: "17" },
        { day: "Wed", codekata: " 5" },
        { day: "Thu", codekata: "25" },
        { day: "Fri", codekata: "10" },
        { day: "Sat", codekata: " 2" },
      ],
      webkata: [
        { day: "Sun", webkata: "13" },
        { day: "Mon", webkata: "10" },
        { day: "Tue", webkata: "17" },
        { day: "Wed", webkata: "5" },
        { day: "Thu", webkata: "25" },
        { day: "Fri", webkata: "10" },
        { day: "Sat", webkata: "20" },
      ],
      tasks: [
        { day: "Sun", completed: "1", pending: "28" },
        { day: "Mon", completed: "3", pending: "24" },
        { day: "Tue", completed: "0", pending: "24" },
        { day: "Wed", completed: "2", pending: "22" },
        { day: "Thu", completed: "1", pending: "21" },
        { day: "Fri", completed: "4", pending: "17" },
        { day: "Sat", completed: "2", pending: "15" },
      ],
      webcode1: "7",
      webcode2: "8",
      capstone: "7.5",
      mockInterview1: "3",
      mockInterview2: "3.3",
    },
  ];
  